name: build_images

on:
  push:

env:
  DOCKERHUB_USERNAME: lucaiacono
  IMAGE_NAME: k8s-helmfile-dev
  IMAGE_TAG: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKERHUB_USERNAME
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
